### ISSUE TITLE
Debug Action Menu Improvements Aren't Working?

### ISSUE THREAD

**Issue by maarxx** [alextd/RimWorld-TDBug#2]
Hi! Great looking mod! Thanks!

The debug action menu improvements aren't totally working for me. The text field doesn't start with focus, and I can't hit the arrow keys to jump between several potential matches.

(( Other parts are working. I see the yellow glow at the top for god mode. ))

**Comment by alextd** [comment]
Ah yea I noticed that. Haven’t played RimWorld enough to fix it.

A patch or so ago a lot of the debug action menu functionality was added in vanilla ... albeit not all of it, so now my parts are broken, some parts work. Didn’t look into it.

**Comment by maarxx** [comment]
For anyone who finds their way here, I fixed the issue with the debug action text box not having keyboard focus, and it wasn't a code change, it was just a matter of adding the newest references, recompiling, and dragging the assembly from `./Assemblies/` (where Visual Studio outputs) into `./1.1/Assemblies/` (what RimWorld seems to actually use, I think?)

**Comment by maarxx** [comment]
I haven't fixed the problem with keyboard up/down arrows not scrolling through multiple potential matches, but that's not a high priority for me.

**Comment by alextd** [comment]
This seems to be good now. Arrows, not so much - the UI was changed there. But there's tab-selection now so that'll work.
